name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo "##[set-output name=NODE_VERSION;]$(cat ./core/.nvmrc)"
        id: nvmrc
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}"
      - name: Install dependencies (core)
        working-directory: ./core
        run: yarn install (core)
      - name: Build core
        working-directory: ./core
        run: yarn build
      - name: Lint source code (core)
        working-directory: ./core
        run: yarn lint
      - name: Install dependencies (cli)
        working-directory: ./cli
        run: yarn install (cli)
      - name: Build cli
        working-directory: ./cli
        run: yarn build
      - name: Lint source code (cli)
        working-directory: ./cli
        run: yarn lint
